name: 'Hamlet Go'
description: 'Perform Hamlet CLI tasks from within a GitHub Action'
inputs:
  task_build_schemas:
    description: 'Generate Hamlet Schemas'
    default: false
  task_build_schemas_output:
    description: 'Directory within the container to output the schemas. Workspace mounts to: /github/workspace'
    default: '/github/workspace'
  properties_file_path:
    description: Path to a properties file containing environment variables
    default: ""
  refresh_output_dir:
    description: Delete content in the output directory before other tasks
    default: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.task_build_schemas }}
    - ${{ inputs.task_build_schemas_output }}
    - ${{ inputs.properties_file_path }}
    - ${{ inputs.refresh_output_dir }}