#!/bin/bash
schemas_output_dir="$1"

hamlet -i mock -p shared -p aws -p azure schema create-schemas -o "$schemas_output_dir"

# Remove Generated Contracts
rm "${schemas_output_dir}"/schema-*-generation-contract.json
